version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
      - command
artifacts:
  files:
    - target\restful-web-microser-0.0.1-SNAPSHOT.jar